CREATE TABLE IF NOT EXISTS module_data_1 (
    id BIGINT PRIMARY KEY DEFAULT nextval('record_sequence'),
    module_id BIGINT NOT NULL,
    created_time BIGINT,
    modified_time BIGINT,
    created_by BIGINT,
    modified_by BIGINT,
    owner BIGINT,

    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    FOREIGN KEY (modified_by) REFERENCES users(user_id),
    FOREIGN KEY (owner) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS module_data_column_1 (
    id BIGINT PRIMARY KEY, -- Matches `id` in `module_1_data`
    string_column1 VARCHAR(255), -- Dynamic field 1 (e.g., name)
    string_column2 VARCHAR(255), -- Dynamic field 2 (e.g., email)
    string_column3 VARCHAR(255),
    string_column4 VARCHAR(255),
    string_column5 VARCHAR(255),
    string_column6 VARCHAR(255),
    string_column7 VARCHAR(255),
    string_column8 VARCHAR(255),
    string_column9 VARCHAR(255),
    string_column10 VARCHAR(255),
    string_column11 VARCHAR(255),
    string_column12 VARCHAR(255),
    string_column13 VARCHAR(255),
    string_column14 VARCHAR(255),
    string_column15 VARCHAR(255),
    string_column16 VARCHAR(255),
    string_column17 VARCHAR(255),
    string_column18 VARCHAR(255),
    string_column19 VARCHAR(255),
    string_column20 VARCHAR(255),
    string_column21 VARCHAR(255),
    string_column22 VARCHAR(255),
    string_column23 VARCHAR(255),
    string_column24 VARCHAR(255),
    string_column25 VARCHAR(255),
    string_column26 VARCHAR(255),
    string_column27 VARCHAR(255),
    string_column28 VARCHAR(255),
    string_column29 VARCHAR(255),
    string_column30 VARCHAR(255),
    string_column31 VARCHAR(255),
    string_column32 VARCHAR(255),
    string_column33 VARCHAR(255),
    string_column34 VARCHAR(255),
    string_column35 VARCHAR(255),
    string_column36 VARCHAR(255),
    string_column37 VARCHAR(255),
    string_column38 VARCHAR(255),
    string_column39 VARCHAR(255),
    string_column40 VARCHAR(255),
    int_column1 INTEGER,
    int_column2 INTEGER,
    int_column3 INTEGER,
    int_column4 INTEGER,
    int_column5 INTEGER,
    int_column6 INTEGER,
    int_column7 INTEGER,
    int_column8 INTEGER,
    int_column9 INTEGER,
    int_column10 INTEGER,
    int_column11 INTEGER,
    int_column12 INTEGER,
    int_column13 INTEGER,
    int_column14 INTEGER,
    int_column15 INTEGER,
    int_column16 INTEGER,
    int_column17 INTEGER,
    int_column18 INTEGER,
    int_column19 INTEGER,
    int_column20 INTEGER,
    int_column21 INTEGER,
    int_column22 INTEGER,
    int_column23 INTEGER,
    int_column24 INTEGER,
    int_column25 INTEGER,
    boolean_column1 BOOLEAN,
    boolean_column2 BOOLEAN,
    boolean_column3 BOOLEAN,
    boolean_column4 BOOLEAN,
    boolean_column5 BOOLEAN,
    boolean_column6 BOOLEAN,
    boolean_column7 BOOLEAN,
    boolean_column8 BOOLEAN,
    boolean_column9 BOOLEAN,
    boolean_column10 BOOLEAN,
    
    text_column1 TEXT,
    text_column2 TEXT,
    text_column3 TEXT,
    text_column4 TEXT,
    text_column5 TEXT,
    

    FOREIGN KEY (id) REFERENCES module_data_1(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS module_data_2 (
    id BIGINT PRIMARY KEY DEFAULT nextval('record_sequence'),
    module_id BIGINT NOT NULL,
    created_time BIGINT,
    modified_time BIGINT,
    created_by BIGINT,
    modified_by BIGINT,
    owner BIGINT,

    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    FOREIGN KEY (modified_by) REFERENCES users(user_id),
    FOREIGN KEY (owner) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS module_data_column_2 (
    id BIGINT PRIMARY KEY, -- Matches `id` in `module_1_data`
    string_column1 VARCHAR(255), -- Dynamic field 1 (e.g., name)
    string_column2 VARCHAR(255), -- Dynamic field 2 (e.g., email)
    string_column3 VARCHAR(255),
    string_column4 VARCHAR(255),
    string_column5 VARCHAR(255),
    string_column6 VARCHAR(255),
    string_column7 VARCHAR(255),
    string_column8 VARCHAR(255),
    string_column9 VARCHAR(255),
    string_column10 VARCHAR(255),
    string_column11 VARCHAR(255),
    string_column12 VARCHAR(255),
    string_column13 VARCHAR(255),
    string_column14 VARCHAR(255),
    string_column15 VARCHAR(255),
    string_column16 VARCHAR(255),
    string_column17 VARCHAR(255),
    string_column18 VARCHAR(255),
    string_column19 VARCHAR(255),
    string_column20 VARCHAR(255),
    string_column21 VARCHAR(255),
    string_column22 VARCHAR(255),
    string_column23 VARCHAR(255),
    string_column24 VARCHAR(255),
    string_column25 VARCHAR(255),
    string_column26 VARCHAR(255),
    string_column27 VARCHAR(255),
    string_column28 VARCHAR(255),
    string_column29 VARCHAR(255),
    string_column30 VARCHAR(255),
    string_column31 VARCHAR(255),
    string_column32 VARCHAR(255),
    string_column33 VARCHAR(255),
    string_column34 VARCHAR(255),
    string_column35 VARCHAR(255),
    string_column36 VARCHAR(255),
    string_column37 VARCHAR(255),
    string_column38 VARCHAR(255),
    string_column39 VARCHAR(255),
    string_column40 VARCHAR(255),
    int_column1 INTEGER,
    int_column2 INTEGER,
    int_column3 INTEGER,
    int_column4 INTEGER,
    int_column5 INTEGER,
    int_column6 INTEGER,
    int_column7 INTEGER,
    int_column8 INTEGER,
    int_column9 INTEGER,
    int_column10 INTEGER,
    int_column11 INTEGER,
    int_column12 INTEGER,
    int_column13 INTEGER,
    int_column14 INTEGER,
    int_column15 INTEGER,
    int_column16 INTEGER,
    int_column17 INTEGER,
    int_column18 INTEGER,
    int_column19 INTEGER,
    int_column20 INTEGER,
    int_column21 INTEGER,
    int_column22 INTEGER,
    int_column23 INTEGER,
    int_column24 INTEGER,
    int_column25 INTEGER,
    boolean_column1 BOOLEAN,
    boolean_column2 BOOLEAN,
    boolean_column3 BOOLEAN,
    boolean_column4 BOOLEAN,
    boolean_column5 BOOLEAN,
    boolean_column6 BOOLEAN,
    boolean_column7 BOOLEAN,
    boolean_column8 BOOLEAN,
    boolean_column9 BOOLEAN,
    boolean_column10 BOOLEAN,
    
    text_column1 TEXT,
    text_column2 TEXT,
    text_column3 TEXT,
    text_column4 TEXT,
    text_column5 TEXT,
    

    FOREIGN KEY (id) REFERENCES module_data_2(id) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS module_data_3 (
    id BIGINT PRIMARY KEY DEFAULT nextval('record_sequence'),
    module_id BIGINT NOT NULL,
    created_time BIGINT,
    modified_time BIGINT,
    created_by BIGINT,
    modified_by BIGINT,
    owner BIGINT,

    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    FOREIGN KEY (modified_by) REFERENCES users(user_id),
    FOREIGN KEY (owner) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS module_data_column_3 (
    id BIGINT PRIMARY KEY, -- Matches `id` in `module_1_data`
    string_column1 VARCHAR(255), -- Dynamic field 1 (e.g., name)
    string_column2 VARCHAR(255), -- Dynamic field 2 (e.g., email)
    string_column3 VARCHAR(255),
    string_column4 VARCHAR(255),
    string_column5 VARCHAR(255),
    string_column6 VARCHAR(255),
    string_column7 VARCHAR(255),
    string_column8 VARCHAR(255),
    string_column9 VARCHAR(255),
    string_column10 VARCHAR(255),
    string_column11 VARCHAR(255),
    string_column12 VARCHAR(255),
    string_column13 VARCHAR(255),
    string_column14 VARCHAR(255),
    string_column15 VARCHAR(255),
    string_column16 VARCHAR(255),
    string_column17 VARCHAR(255),
    string_column18 VARCHAR(255),
    string_column19 VARCHAR(255),
    string_column20 VARCHAR(255),
    string_column21 VARCHAR(255),
    string_column22 VARCHAR(255),
    string_column23 VARCHAR(255),
    string_column24 VARCHAR(255),
    string_column25 VARCHAR(255),
    string_column26 VARCHAR(255),
    string_column27 VARCHAR(255),
    string_column28 VARCHAR(255),
    string_column29 VARCHAR(255),
    string_column30 VARCHAR(255),
    string_column31 VARCHAR(255),
    string_column32 VARCHAR(255),
    string_column33 VARCHAR(255),
    string_column34 VARCHAR(255),
    string_column35 VARCHAR(255),
    string_column36 VARCHAR(255),
    string_column37 VARCHAR(255),
    string_column38 VARCHAR(255),
    string_column39 VARCHAR(255),
    string_column40 VARCHAR(255),
    int_column1 INTEGER,
    int_column2 INTEGER,
    int_column3 INTEGER,
    int_column4 INTEGER,
    int_column5 INTEGER,
    int_column6 INTEGER,
    int_column7 INTEGER,
    int_column8 INTEGER,
    int_column9 INTEGER,
    int_column10 INTEGER,
    int_column11 INTEGER,
    int_column12 INTEGER,
    int_column13 INTEGER,
    int_column14 INTEGER,
    int_column15 INTEGER,
    int_column16 INTEGER,
    int_column17 INTEGER,
    int_column18 INTEGER,
    int_column19 INTEGER,
    int_column20 INTEGER,
    int_column21 INTEGER,
    int_column22 INTEGER,
    int_column23 INTEGER,
    int_column24 INTEGER,
    int_column25 INTEGER,
    boolean_column1 BOOLEAN,
    boolean_column2 BOOLEAN,
    boolean_column3 BOOLEAN,
    boolean_column4 BOOLEAN,
    boolean_column5 BOOLEAN,
    boolean_column6 BOOLEAN,
    boolean_column7 BOOLEAN,
    boolean_column8 BOOLEAN,
    boolean_column9 BOOLEAN,
    boolean_column10 BOOLEAN,
    
    text_column1 TEXT,
    text_column2 TEXT,
    text_column3 TEXT,
    text_column4 TEXT,
    text_column5 TEXT,
    

    FOREIGN KEY (id) REFERENCES module_data_3(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS module_data_4 (
    id BIGINT PRIMARY KEY DEFAULT nextval('record_sequence'),
    module_id BIGINT NOT NULL,
    created_time BIGINT,
    modified_time BIGINT,
    created_by BIGINT,
    modified_by BIGINT,
    owner BIGINT,

    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    FOREIGN KEY (modified_by) REFERENCES users(user_id),
    FOREIGN KEY (owner) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS module_data_column_4 (
    id BIGINT PRIMARY KEY, -- Matches `id` in `module_1_data`
    string_column1 VARCHAR(255), -- Dynamic field 1 (e.g., name)
    string_column2 VARCHAR(255), -- Dynamic field 2 (e.g., email)
    string_column3 VARCHAR(255),
    string_column4 VARCHAR(255),
    string_column5 VARCHAR(255),
    string_column6 VARCHAR(255),
    string_column7 VARCHAR(255),
    string_column8 VARCHAR(255),
    string_column9 VARCHAR(255),
    string_column10 VARCHAR(255),
    string_column11 VARCHAR(255),
    string_column12 VARCHAR(255),
    string_column13 VARCHAR(255),
    string_column14 VARCHAR(255),
    string_column15 VARCHAR(255),
    string_column16 VARCHAR(255),
    string_column17 VARCHAR(255),
    string_column18 VARCHAR(255),
    string_column19 VARCHAR(255),
    string_column20 VARCHAR(255),
    string_column21 VARCHAR(255),
    string_column22 VARCHAR(255),
    string_column23 VARCHAR(255),
    string_column24 VARCHAR(255),
    string_column25 VARCHAR(255),
    string_column26 VARCHAR(255),
    string_column27 VARCHAR(255),
    string_column28 VARCHAR(255),
    string_column29 VARCHAR(255),
    string_column30 VARCHAR(255),
    string_column31 VARCHAR(255),
    string_column32 VARCHAR(255),
    string_column33 VARCHAR(255),
    string_column34 VARCHAR(255),
    string_column35 VARCHAR(255),
    string_column36 VARCHAR(255),
    string_column37 VARCHAR(255),
    string_column38 VARCHAR(255),
    string_column39 VARCHAR(255),
    string_column40 VARCHAR(255),
    int_column1 INTEGER,
    int_column2 INTEGER,
    int_column3 INTEGER,
    int_column4 INTEGER,
    int_column5 INTEGER,
    int_column6 INTEGER,
    int_column7 INTEGER,
    int_column8 INTEGER,
    int_column9 INTEGER,
    int_column10 INTEGER,
    int_column11 INTEGER,
    int_column12 INTEGER,
    int_column13 INTEGER,
    int_column14 INTEGER,
    int_column15 INTEGER,
    int_column16 INTEGER,
    int_column17 INTEGER,
    int_column18 INTEGER,
    int_column19 INTEGER,
    int_column20 INTEGER,
    int_column21 INTEGER,
    int_column22 INTEGER,
    int_column23 INTEGER,
    int_column24 INTEGER,
    int_column25 INTEGER,
    boolean_column1 BOOLEAN,
    boolean_column2 BOOLEAN,
    boolean_column3 BOOLEAN,
    boolean_column4 BOOLEAN,
    boolean_column5 BOOLEAN,
    boolean_column6 BOOLEAN,
    boolean_column7 BOOLEAN,
    boolean_column8 BOOLEAN,
    boolean_column9 BOOLEAN,
    boolean_column10 BOOLEAN,

    text_column1 TEXT,
    text_column2 TEXT,
    text_column3 TEXT,
    text_column4 TEXT,
    text_column5 TEXT,
    

    FOREIGN KEY (id) REFERENCES module_data_4(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS module_data_5 (
    id BIGINT PRIMARY KEY DEFAULT nextval('record_sequence'),
    module_id BIGINT NOT NULL,
    created_time BIGINT,
    modified_time BIGINT,
    created_by BIGINT,
    modified_by BIGINT,
    owner BIGINT,

    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    FOREIGN KEY (modified_by) REFERENCES users(user_id),
    FOREIGN KEY (owner) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS module_data_column_5 (
    id BIGINT PRIMARY KEY, -- Matches `id` in `module_1_data`
    string_column1 VARCHAR(255), -- Dynamic field 1 (e.g., name)
    string_column2 VARCHAR(255), -- Dynamic field 2 (e.g., email)
    string_column3 VARCHAR(255),
    string_column4 VARCHAR(255),
    string_column5 VARCHAR(255),
    string_column6 VARCHAR(255),
    string_column7 VARCHAR(255),
    string_column8 VARCHAR(255),
    string_column9 VARCHAR(255),
    string_column10 VARCHAR(255),
    string_column11 VARCHAR(255),
    string_column12 VARCHAR(255),
    string_column13 VARCHAR(255),
    string_column14 VARCHAR(255),
    string_column15 VARCHAR(255),
    string_column16 VARCHAR(255),
    string_column17 VARCHAR(255),
    string_column18 VARCHAR(255),
    string_column19 VARCHAR(255),
    string_column20 VARCHAR(255),
    string_column21 VARCHAR(255),
    string_column22 VARCHAR(255),
    string_column23 VARCHAR(255),
    string_column24 VARCHAR(255),
    string_column25 VARCHAR(255),
    string_column26 VARCHAR(255),
    string_column27 VARCHAR(255),
    string_column28 VARCHAR(255),
    string_column29 VARCHAR(255),
    string_column30 VARCHAR(255),
    string_column31 VARCHAR(255),
    string_column32 VARCHAR(255),
    string_column33 VARCHAR(255),
    string_column34 VARCHAR(255),
    string_column35 VARCHAR(255),
    string_column36 VARCHAR(255),
    string_column37 VARCHAR(255),
    string_column38 VARCHAR(255),
    string_column39 VARCHAR(255),
    string_column40 VARCHAR(255),
    int_column1 INTEGER,
    int_column2 INTEGER,
    int_column3 INTEGER,
    int_column4 INTEGER,
    int_column5 INTEGER,
    int_column6 INTEGER,
    int_column7 INTEGER,
    int_column8 INTEGER,
    int_column9 INTEGER,
    int_column10 INTEGER,
    int_column11 INTEGER,
    int_column12 INTEGER,
    int_column13 INTEGER,
    int_column14 INTEGER,
    int_column15 INTEGER,
    int_column16 INTEGER,
    int_column17 INTEGER,
    int_column18 INTEGER,
    int_column19 INTEGER,
    int_column20 INTEGER,
    int_column21 INTEGER,
    int_column22 INTEGER,
    int_column23 INTEGER,
    int_column24 INTEGER,
    int_column25 INTEGER,
    boolean_column1 BOOLEAN,
    boolean_column2 BOOLEAN,
    boolean_column3 BOOLEAN,
    boolean_column4 BOOLEAN,
    boolean_column5 BOOLEAN,
    boolean_column6 BOOLEAN,
    boolean_column7 BOOLEAN,
    boolean_column8 BOOLEAN,
    boolean_column9 BOOLEAN,
    boolean_column10 BOOLEAN,

    text_column1 TEXT,
    text_column2 TEXT,
    text_column3 TEXT,
    text_column4 TEXT,
    text_column5 TEXT,
    

    FOREIGN KEY (id) REFERENCES module_data_5(id) ON DELETE CASCADE
);